#!/usr/bin/env python3
"""
AI Writer module - generates markdown from extracted text
"""

import os

def generate_markdown(raw_text, url, media_type, collection, config):
    """Generate structured markdown from extracted text"""
    
    # Simple template for now - can be enhanced with actual AI API
    title = f"Instagram {media_type.title()}"
    
    markdown = f"""---
url: {url}
type: {media_type}
collection: {collection}
---

# {title}

## Summary
Content extracted from Instagram {media_type}.

## Key Points
- Content type: {media_type}
- Source: Instagram
- Collection: {collection}

## Full Text

```text
{raw_text}
```

---
*Generated by IG Content Extractor*
"""
    
    return markdown
